### ISSUE TITLE
Compatibility with Zabbix 3.2.6?

### ISSUE THREAD

**Issue by iFedix** [fredprod/logstash-zabbix#3]
When I tried to import he template it told me that the version was unsupported. I changed     this `<version>3.4</version>` to  `<version>2.0</version>`. Now the error while importing is: 
`Invalid tag "/zabbix_export/templates/template(1)": unexpected tag "httptests".`
Also changing version to 3.2.6 told me unsupported version.
Any update on this?

**Comment by fredprod** [comment]
Sorry, I will push another version of Template to be compliant with zabbix 3.2 versions.

**Comment by fredprod** [comment]
I have just upload Template working on 3.2 version.

**Comment by iFedix** [comment]
@fredprod thank you a lot! :)
