### ISSUE TITLE
Step 2 - Get Data failed ['pipeline']

### ISSUE THREAD

**Issue by nicomagliaro** [fredprod/logstash-zabbix#5]
Hi there!
Sorry but I'm having a hard time to implement the script into zabbix.
When I run the command:

> /etc/zabbix/scripts/logstash.py -v -d --update-items

I get
> [LogstashServer:CRITICAL] Step 2 - Get Data failed ['pipeline']
> 2

I've checked out and is correctly trying to query this url within logstash server
> http://localhost:9600/_node/stats/

If I curl this url, I get a json object (logstash host and port is OK) so I'm confused why I cannot advance to next steps and protobix cannot populate data object.
**curl http://localhost:9600/_node/stats/**
`{"host":"Logstash2","version":"6.2.2","http_address":"127.0.0.1:9600","id":"b99a2d92-3c8d-4423-9fd0-c45e1ba62fcf","name":"Logstash2","jvm":{"threads":{"count":74,"peak_count":80},"mem":{"heap_used_percent":20,"heap_committed_in_bytes":385245184,"heap_max_in_bytes":1037959168,"heap_used_in_bytes":209778568,"non_heap_used_in_bytes":193024872,"non_heap_committed_in_bytes":217378816,"pools":{"survivor":{"peak_used_in_bytes":8912896,"used_in_bytes":784128,"peak_max_in_bytes":35782656,"max_in_bytes":35782656,"committed_in_bytes":8912896},"old":{"peak_used_in_bytes":293835960,"used_in_bytes":166209160,"peak_max_in_bytes":715849728,"max_in_bytes":715849728,"committed_in_bytes":304701440},"young":{"peak_used_in_bytes":71630848,"used_in_bytes":42785280,"peak_max_in_bytes":286326784,"max_in_bytes":286326784,"committed_in_bytes":71630848}}},"gc":{"collectors":{"old":{"collection_time_in_millis":133179,"collection_count":1857},"young":{"collection_time_in_millis":434618,"collection_count":52398}}},"uptime_in_millis":356991575},"process":{"open_file_descriptors":182,"peak_open_file_descriptors":9381,"max_file_descriptors":16384,"mem":{"total_virtual_in_bytes":10598539264},"cpu":{"total_in_millis":44406810,"percent":0,"load_average":{"1m":0.63,"5m":0.68,"15m":0.68}}},"events":{"in":19834714,"filtered":19834708,"out":19834708,"duration_in_millis":405190918,"queue_push_duration_in_millis":105983788},"pipelines":{"main":{"events":{"duration_in_millis":405190918,"in":19834714,"filtered":19834708,"out":19834708,"queue_push_duration_in_millis":105983788},"plugins":{"inputs":[{"id":"aca155086f44959a40e37803ec1cfe9cd1be17cd23e98ce6ca57b2b8d06a65c7","events":{"out":6872,"queue_push_duration_in_millis":33992},"name":"http"},{"id":"b52994e164e59371561bd6673ac6a679827b9ff377e1b1ef0dbbca5f528439b5","events":{"out":19766729,"queue_push_duration_in_millis":104817716},"name":"http"},{"id":"73cbdcf05be4d0cb93268fa02d84c4b3baefe6e1ad3faae58dd54d9c6a3a04ef","events":{"out":5593,"queue_push_duration_in_millis":58422},"name":"http"},{"id":"a2f5883b469a2fc60437d173f618515fa48c512cacc112ac04eedad1d6698009","events":{"out":55520,"queue_push_duration_in_millis":1073658},"name":"http"}],"filters":[{"id":"4e08d145f01ecd3ca0775765bc98894c5ef1c1e01b3c36ff6574ef331f61e627","events":{"duration_in_millis":21073,"in":19834708,"out":19834708},"name":"json"},{"id":"e7dd2b60f02c664799b7ca466f952b682390cfb3b60d3addc459cb4df77f0009","events":{"duration_in_millis":102240,"in":19834708,"out":19834708},"name":"ruby"}],"outputs":[{"id":"e5d33f374b86b76844bb2b2ce458a0ec48d0f0a106297346ce4a1b12e02dfa7d","events":{"duration_in_millis":1635467,"in":6872,"out":6872},"name":"elasticsearch"},{"id":"6792ee686b3442bd7349e3e7baf0923f849e9cbcb0badea7c1ded8811658e2f5","events":{"duration_in_millis":670980,"in":5593,"out":5593},"name":"elasticsearch"},{"id":"98ce77a439534d90a2917e5adfb97f45547cc54a870f5de910838a7727d92ad3","events":{"duration_in_millis":317659694,"in":19766723,"out":19766723},"name":"elasticsearch"}]},"reloads":{"last_error":null,"successes":0,"last_success_timestamp":null,"last_failure_timestamp":null,"failures":0},"queue":{"events":0,"type":"persisted","capacity":{"queue_size_in_bytes":26006795,"page_capacity_in_bytes":67108864,"max_queue_size_in_bytes":42949672960,"max_unread_events":0},"data":{"path":"/var/lib/logstash/queue/main","free_space_in_bytes":1831032651776,"storage_type":"rootfs"}}}},"reloads":{"successes":0,"failures":0},"os":{"cgroup":{"cpuacct":{"usage_nanos":225116033431552,"control_group":"/"},"cpu":{"cfs_quota_micros":-1,"control_group":"/","stat":{"number_of_times_throttled":0,"time_throttled_nanos":0,"number_of_elapsed_periods":0},"cfs_period_micros":100000}}}}`

The  **/etc/zabbix/scripts/logstash.py --discovery** exit with 0 value

The zabbix agent config path is default.
Any thoughts come to your mind?

Thanks in advance!

**Comment by fredprod** [comment]
There is some issues with logstash v6.x. I will post tomorrow Paris time a Python script that fit these versions.

**Comment by fredprod** [comment]
I have just added new script for version 6.x of logstash. A new template for Zabbix too, only 3.4. Tell me if you need an older version of template.

**Comment by nicomagliaro** [comment]
Thanks a lot man! 
Also I think there is a typo
` # Process global events metrics
        zbx_key = 'logstash.pipeline.events.{0}'
        for events_section in nodes_stats['events']:
            if not isinstance(nodes_stats['events'][events_section], dict):
                data[zbx_key.format(events_section)] = nodes_stats['events'][events_section]
            else:
                real_key = zbx_key.format(events_section) + '.{0}'
                data.update(
                    self._process_items(real_key, **odes_stats[**'events'][events_section])
                )`

I change it to:
` # Process global events metrics
        zbx_key = 'logstash.pipeline.events.{0}'
        for events_section in nodes_stats['events']:
            if not isinstance(nodes_stats['events'][events_section], dict):
                data[zbx_key.format(events_section)] = nodes_stats['events'][events_section]
            else:
                real_key = zbx_key.format(events_section) + '.{0}'
                data.update(
                    self._process_items(real_key, nodes_stats['events'][events_section])
                )`

Br

**Comment by fredprod** [comment]
Thx nicomagliaro. It is now fixed.
