### ISSUE TITLE
Parser failed with several errors

### ISSUE THREAD

**Issue by alanwds** [fredprod/logstash-zabbix#7]
Hi,

I'm trying use the script to collect data and i'm getting the following error?

```
/usr/local/bin/logstash.py --update-items -d -vvvv
Traceback (most recent call last):
  File "/usr/local/bin/logstash.py", line 112, in <module>
    ret = LogstashServer().run()
  File "/usr/lib/python2.7/site-packages/protobix/sampleprobe.py", line 281, in run
    self.zbx_config = self._init_config()
  File "/usr/lib/python2.7/site-packages/protobix/sampleprobe.py", line 204, in _init_config
    zbx_config = ZabbixAgentConfig(self.options.config_file)
  File "/usr/lib/python2.7/site-packages/protobix/zabbixagentconfig.py", line 56, in __init__
    tmp_config = configobj.ConfigObj(config_file, list_values=False)
  File "/usr/lib/python2.7/site-packages/configobj.py", line 1229, in __init__
    self._load(infile, configspec)
  File "/usr/lib/python2.7/site-packages/configobj.py", line 1318, in _load
    raise error
configobj.ConfigObjError: Parsing failed with several errors.
First error at line 299.
```

I already try set the host of LS (i'm binding at the local valid interface insted of localhost).

Do you know the reason for that? I'm facing a bug?

Python: 2.7
Protobix: 1.0.1
Pip: 9.0.2
LS: 5.6.8
Zabbix: 3.2

Regards,
Alan Santos

**Comment by fredprod** [comment]
Can you check zabbix_agentd.conf location?

**Comment by alanwds** [comment]
Hi @fredprod,

Thank your support. I already check it. The help is very clear about it (congrats for that :). My zabbix_agentd.conf is in the default path (/etc/zabbix/zabbix_agentd.conf).

But, your comment give me a chance. Looking for this errors, looks like a parser issue (that is the reason you told me check the zabbix_agentd.conf). I get my zabbix_agentd.conf and get some User Parameters in there insted of a separate file at /etc/zabbix/zabbix_agentd/ folder. I remove those lines and create a new file in corret path and the problem was solved.

Thank you again by your help and sorry for open a false-positive issue.

Just to know, these are the "bad User Parameters":

```
UserParameter=sockstat.sockets,cat /proc/net/sockstat|grep sockets|cut -d' ' -f 3
UserParameter=sockstat.tcp.inuse,cat /proc/net/sockstat|grep TCP|cut -d' ' -f 3
UserParameter=sockstat.tcp.orphan,cat /proc/net/sockstat|grep TCP|cut -d' ' -f 5
UserParameter=sockstat.tcp.timewait,cat /proc/net/sockstat|grep TCP|cut -d' ' -f 7
UserParameter=sockstat.tcp.allocated,cat /proc/net/sockstat|grep TCP|cut -d' ' -f 9
UserParameter=sockstat.tcp.mem,cat /proc/net/sockstat|grep TCP|cut -d' ' -f 11
UserParameter=sockstat.udp.inuse,cat /proc/net/sockstat|grep UDP:|cut -d' ' -f 3
UserParameter=sockstat.udp.mem,cat /proc/net/sockstat|grep UDP:|cut -d' ' -f 5
```
I use them to collect socket information about the host. I suspect that the pipe or the quotes break the parser.

Best Regards,
Alan Santos

**Comment by fredprod** [comment]
Hi @alanwds thx for your explanation too about your issue, I hope it can help other people with same issue.
Regards,
Frederic
