### ISSUE TITLE
Unable to discovery items

### ISSUE THREAD

**Issue by alanwds** [fredprod/logstash-zabbix#8]
Hi,

I'm trying use the logstash.py script to discovery and send data, but always get items:

```
/usr/local/bin/logstash.py -H LS_INSTANCE --discovery -vvvv

[LogstashServer:INFO] Starting to send 0 items
[LogstashServer:DEBUG] Bulk limit is 1 items
[LogstashServer:INFO] All 0 items have been sent in 0 runs
[LogstashServer:DEBUG] Total run is 0; item processed: 0, failed: 0, total: 0, during 0.000000 seconds
[LogstashServer:INFO] Reset DataContainer
0
```

I also tryed use zabbix_get to discovery items:

`zabbix_get -s LS_INSTANCE -p 10050 -k 'logstash.discovery'
`
But the result is always 0:

```
zabbix_get -s logstash-analytics-prd1.dc.sensedia.com.br -p 10050 -k 'logstash.discovery'
0
```

My versions:
Python: 2.7
Protobix: 1.0.1
Pip: 9.0.2
LS: 5.6.8
Zabbix: 3.2
Zabbix_agent: 3.2.11

Is that normal or am i losing something?

Best Regards,
Alan Santos

**Comment by fredprod** [comment]
Hi, at that time, yes discovery does nothing, it is for future purpose. I didn't have enough time sorry.

**Comment by alanwds** [comment]
I'm asking because i did all the setup but it's not possible see any data at zabbix. I was thinking that is the reason. Probably, i'm losing something. Running script with --update-items parmeters, i'm able to get all itens, but nothing is showed in zabbix server.

Regards,
Alan Santos

**Comment by fredprod** [comment]
Can you paste result of update-items cmd? Only INFO level will be enough. You should have something like this:
[LogstashServer:INFO] Starting to send 43 items
[LogstashServer:INFO] Bulk limit is 250 items
[LogstashServer:INFO] Send data to Zabbix Server
[LogstashServer:INFO] Creating new socket
[LogstashServer:INFO] Network socket initialized with no TLS
[LogstashServer:INFO] Reading Zabbix Server's answer
[LogstashServer:INFO] Anaylizing Zabbix Server's answer
[LogstashServer:INFO] Send result [42-1-43] for key [(bulk)] item [(bulk)]. Server's response is success
[LogstashServer:INFO] 43 items sent during run 1
[LogstashServer:INFO] Reset socket
[LogstashServer:INFO] All 43 items have been sent in 1 runs
[LogstashServer:INFO] Reset DataContainer
0

**Comment by alanwds** [comment]
The result is exactly this:

```
/usr/local/bin/logstash.py -H LS_INSTANCE_IP --update-items 
[LogstashServer:INFO] Starting to send 43 items
[LogstashServer:INFO] Bulk limit is 250 items
[LogstashServer:INFO] Send data to Zabbix Server
[LogstashServer:INFO] Creating new socket
[LogstashServer:INFO] Network socket initialized with no TLS
[LogstashServer:INFO] Reading Zabbix Server's answer
[LogstashServer:INFO] Anaylizing Zabbix Server's answer
[LogstashServer:INFO] Send result [0-43-43] for key [(bulk)] item [(bulk)]. Server's response is success
[LogstashServer:INFO] 43 items sent during run 1
[LogstashServer:INFO] Reset socket
[LogstashServer:INFO] All 43 items have been sent in 1 runs
[LogstashServer:INFO] Reset DataContainer
0
```
Howhever, there's nothing on zabbix server, only discovery and check:

![image](https://user-images.githubusercontent.com/13525218/37716453-585098c8-2cfd-11e8-99ce-cab685bdbd34.png)

Regards,
Alan Santos

**Comment by fredprod** [comment]
Ok, so `Send result` says that nothing was sent to Zabbix server. Can you only launch `/usr/local/bin/logstash.py --update-items` from your logstash server? Script will parse zabbix agent configuration from your logstash server. Check that Hostname field is the same between your zabbix agent configuration and the name you entered in Zabbix server frontend? Check [https://www.zabbix.com/documentation/3.4/manual/config/items/itemtypes/trapper](url). When there is an issue between hostname in zabbix agent conf and technical hostname on zabbix server.

**Comment by alanwds** [comment]
Hi @fredprod ,

I'm running on LS server. I just pass the -H parameter because my logstash listen on the valid interface (insted of localhost).

I also check the hostname on zabbix_agent.conf and zabbix server and is the same (i use auto registry feature to avoid this kind of issue).

Regards,
Alan Santos

**Comment by fredprod** [comment]
Can you add a `print data` in function _get_metrics of logstash.py, just above return data, to check if there is an issue with json data? Have you open port 10051 from LS server to Zabbix server?

**Comment by alanwds** [comment]
Sure.. please, check the result bellow:

```
 /usr/local/bin/logstash.py -H LS_HOSTNAME --update-items
{'LS_HOSTNAME': {'logstash.jvm.mem.pools.young.committed_in_bytes': 139591680, 'logstash.pipeline.events.queue_push_duration_in_millis': 12196, 'logstash.pipeline.events.duration_in_millis': 47037, 'logstash.jvm.mem.pools.survivor.max_in_bytes': 17432576, 'logstash.jvm.gc.collectors.old.collection_time_in_millis': 223, 'logstash.process.cpu.total_in_millis': 343910, 'logstash.jvm.mem.pools.young.max_in_bytes': 139591680, 'logstash.jvm.mem.pools.survivor.peak_max_in_bytes': 17432576, 'logstash.jvm.gc.collectors.young.collection_count': 244, 'logstash.jvm.threads.count': 28, 'logstash.process.peak_open_file_descriptors': 111, 'logstash.process.mem.total_virtual_in_bytes': 5963575296, 'logstash.process.max_file_descriptors': 16384, 'logstash.jvm.mem.non_heap_used_in_bytes': 116716928, 'logstash.jvm.mem.pools.young.peak_max_in_bytes': 139591680, 'logstash.jvm.mem.pools.survivor.committed_in_bytes': 17432576, 'logstash.pipeline.events.filtered': 1192, 'logstash.jvm.mem.heap_used_percent': 4, 'logstash.jvm.mem.pools.old.used_in_bytes': 73926560, 'logstash.jvm.mem.pools.old.max_in_bytes': 3046768640, 'logstash.jvm.gc.collectors.old.collection_count': 2, 'logstash.jvm.mem.pools.young.peak_used_in_bytes': 139591680, 'logstash.jvm.mem.pools.young.used_in_bytes': 69493072, 'logstash.pipeline.events.out': 1192, 'logstash.jvm.uptime_in_millis': 10681205, 'logstash.jvm.mem.non_heap_committed_in_bytes': 124227584, 'logstash.jvm.mem.pools.survivor.used_in_bytes': 631040, 'logstash.pipeline.events.in': 596, 'logstash.jvm.mem.heap_max_in_bytes': 3203792896, 'logstash.jvm.mem.pools.old.committed_in_bytes': 899284992, 'logstash.jvm.mem.pools.old.peak_used_in_bytes': 104578416, 'logstash.jvm.gc.collectors.young.collection_time_in_millis': 2364, 'logstash.jvm.mem.heap_used_in_bytes': 144050672, 'logstash.process.cpu.load_average.15m': 0.05, 'logstash.process.open_file_descriptors': 99, 'logstash.process.cpu.percent': 1, 'logstash.jvm.threads.peak_count': 30, 'logstash.zbx_version': '0.0.1', 'logstash.jvm.mem.pools.old.peak_max_in_bytes': 3046768640, 'logstash.process.cpu.load_average.5m': 0.06, 'logstash.jvm.mem.heap_committed_in_bytes': 1056309248, 'logstash.process.cpu.load_average.1m': 0.05, 'logstash.jvm.mem.pools.survivor.peak_used_in_bytes': 17432576}}
[LogstashServer:INFO] Starting to send 43 items
[LogstashServer:INFO] Bulk limit is 250 items
[LogstashServer:INFO] Send data to Zabbix Server
[LogstashServer:INFO] Creating new socket
[LogstashServer:INFO] Network socket initialized with no TLS
[LogstashServer:INFO] Reading Zabbix Server's answer
[LogstashServer:INFO] Anaylizing Zabbix Server's answer
[LogstashServer:INFO] Send result [0-43-43] for key [(bulk)] item [(bulk)]. Server's response is success
[LogstashServer:INFO] 43 items sent during run 1
[LogstashServer:INFO] Reset socket
[LogstashServer:INFO] All 43 items have been sent in 1 runs
[LogstashServer:INFO] Reset DataContainer
0
```

Regards,
Alan Santos

**Comment by fredprod** [comment]
Ok json seems ok. In latest data on Zabbix frontend with Show items without data checked, have you all Application of Template Logstash?
![screen shot](https://user-images.githubusercontent.com/10994072/37719762-0a688836-2d26-11e8-8fe8-511fec6f5c79.png)
You have no errors in zabbix agent log or zabbix server log?

**Comment by alanwds** [comment]
There are access between LS server and zabbix server on port 10051.

The Apps does not exists on latest data. I don't know the reason.

I tryed parser the json (returned by print data) with jq and got an error. Look's like a quote issue. I did a sed change single-quote by double-quotes and i'm able to parsing with jq. Maybe the issues are related? Make's sense?

Regards,
Alan Santos

**Comment by alanwds** [comment]
On zabbix_server.log (DebugLevel=5) i got the correct json:

``` 7854:20180321:135319.616 trapper got '{"request": "sender data", "data": [{"host": "LS_HOSTNAME", "state": 0, "value": 139591680, "key": "logstash.jvm.mem.pools.young.committed_in_bytes", "clock": 1521651316}, {"host": "LS_HOSTNAME", "state": 0, "value": 12333, "key": "logstash.pipeline.events.queue_push_duration_in_millis", "clock": 1521651316}, {"host": "LS_HOSTNAME", "state": 0, "value": 50396, "key": "logstash.pipeline.events.duration_in_millis", "clock": 1521651316}, {"host": "LS_HOSTNAME", "state": 0, "value": 17432576, "key": "logstash.jvm.mem.pools.survivor.max_in_bytes", "clock": 1521651316}, {"host": "LS_HOSTNAME", "state": 0, "value": 223, "key": "logstash.jvm.gc.collectors.old.collection_time_in_millis", "clock": 1521651316}, {"host": "LS_HOSTNAME", "state": 0, "value": 473260, "key": "logstash.process.cpu.total_in_millis", "clock": 1521651316}, {"host": "LS_HOSTNAME", "state": 0, "value": 139591680, "key": "logstash.jvm.mem.pools.young.max_in_bytes", "clock": 1521651316}, {"host": "LS_HOSTNAME", "state": 0, "value": 17432576, "key": "logstash.jvm.mem.pools.survivor.peak_max_in_bytes", "clock": 1521651316}, {"host": "LS_HOSTNAME", "state": 0, "value": 352, "key": "logstash.jvm.gc.collectors.young.collection_count", "clock": 1521651316}, {"host": "LS_HOSTNAME", "state": 0, "value": 28, "key": "logstash.jvm.threads.count", "clock": 1521651316}, {"host": "LS_HOSTNAME", "state": 0, "value": 111, "key": "logstash.process.peak_open_file_descriptors", "clock": 1521651316}, {"host": "LS_HOSTNAME", "state": 0, "value": 5963575296, "key": "logstash.process.mem.total_virtual_in_bytes", "clock": 1521651316}, {"host": "LS_HOSTNAME", "state": 0, "value": 16384, "key": "logstash.process.max_file_descriptors", "clock": 1521651316}, {"host": "LS_HOSTNAME", "state": 0, "value": 117198592, "key": "logstash.jvm.mem.non_heap_used_in_bytes", "clock": 1521651316}, {"host": "LS_HOSTNAME", "state": 0, "value": 139591680, "key": "logstash.jvm.mem.pools.young.peak_max_in_bytes", "clock": 1521651316}, {"host": "LS_HOSTNAME", "state": 0, "value": 17432576, "key": "logstash.jvm.mem.pools.survivor.committed_in_bytes", "clock": 1521651316}, {"host": "LS_HOSTNAME", "state": 0, "value": 1328, "key": "logstash.pipeline.events.filtered", "clock": 1521651316}, {"host": "LS_HOSTNAME", "state": 0, "value": 4, "key": "logstash.jvm.mem.heap_used_percent", "clock": 1521651316}, {"host": "LS_HOSTNAME", "state": 0, "value": 74324464, "key": "logstash.jvm.mem.pools.old.used_in_bytes", "clock": 1521651316}, {"host": "LS_HOSTNAME", "state": 0, "value": 3046768640, "key": "logstash.jvm.mem.pools.old.max_in_bytes", "clock": 1521651316}, {"host": "LS_HOSTNAME", "state": 0, "value": 2, "key": "logstash.jvm.gc.collectors.old.collection_count", "clock": 1521651316}, {"host": "LS_HOSTNAME", "state": 0, "value": 139591680, "key": "logstash.jvm.mem.pools.young.peak_used_in_bytes", "clock": 1521651316}, {"host": "LS_HOSTNAME", "state": 0, "value": 61729872, "key": "logstash.jvm.mem.pools.young.used_in_bytes", "clock": 1521651316}, {"host": "LS_HOSTNAME", "state": 0, "value": 1328, "key": "logstash.pipeline.events.out", "clock": 1521651316}, {"host": "LS_HOSTNAME", "state": 0, "value": 15793221, "key": "logstash.jvm.uptime_in_millis", "clock": 1521651316}, {"host": "LS_HOSTNAME", "state": 0, "value": 124882944, "key": "logstash.jvm.mem.non_heap_committed_in_bytes", "clock": 1521651316}, {"host": "LS_HOSTNAME", "state": 0, "value": 610800, "key": "logstash.jvm.mem.pools.survivor.used_in_bytes", "clock": 1521651316}, {"host": "LS_HOSTNAME", "state": 0, "value": 664, "key": "logstash.pipeline.events.in", "clock": 1521651316}, {"host": "LS_HOSTNAME", "state": 0, "value": 3203792896, "key": "logstash.jvm.mem.heap_max_in_bytes", "clock": 1521651316}, {"host": "LS_HOSTNAME", "state": 0, "value": 899284992, "key": "logstash.jvm.mem.pools.old.committed_in_bytes", "clock": 1521651316}, {"host": "LS_HOSTNAME", "state": 0, "value": 104578416, "key": "logstash.jvm.mem.pools.old.peak_used_in_bytes", "clock": 1521651316}, {"host": "LS_HOSTNAME", "state": 0, "value": 3105, "key": "logstash.jvm.gc.collectors.young.collection_time_in_millis", "clock": 1521651316}, {"host": "LS_HOSTNAME", "state": 0, "value": 136665136, "key": "logstash.jvm.mem.heap_used_in_bytes", "clock": 1521651316}, {"host": "LS_HOSTNAME", "state": 0, "value": 0.05, "key": "logstash.process.cpu.load_average.15m", "clock": 1521651316}, {"host": "LS_HOSTNAME", "state": 0, "value": 98, "key": "logstash.process.open_file_descriptors", "clock": 1521651316}, {"host": "LS_HOSTNAME", "state": 0, "value": 1, "key": "logstash.process.cpu.percent", "clock": 1521651316}, {"host": "LS_HOSTNAME", "state": 0, "value": 30, "key": "logstash.jvm.threads.peak_count", "clock": 1521651316}, {"host": "LS_HOSTNAME", "state": 0, "value": "0.0.1", "key": "logstash.zbx_version", "clock": 1521651316}, {"host": "LS_HOSTNAME", "state": 0, "value": 3046768640, "key": "logstash.jvm.mem.pools.old.peak_max_in_bytes", "clock": 1521651316}, {"host": "LS_HOSTNAME", "state": 0, "value": 0.03, "key": "logstash.process.cpu.load_average.5m", "clock": 1521651316}, {"host": "LS_HOSTNAME", "state": 0, "value": 1056309248, "key": "logstash.jvm.mem.heap_committed_in_bytes", "clock": 1521651316}, {"host": "LS_HOSTNAME", "state": 0, "value": 0.08, "key": "logstash.process.cpu.load_average.1m", "clock": 1521651316}, {"host": "LS_HOSTNAME", "state": 0, "value": 17432576, "key": "logstash.jvm.mem.pools.survivor.peak_used_in_bytes", "clock": 1521651316}], "clock": 1521651316}'```

It's really a mistery. The latest data screen still not showing anything.

**Comment by fredprod** [comment]
Can you check if you have uploaded right version of template in Zabbix? Check if you have well linked Template to your host LS_HOSTNAME?

**Comment by alanwds** [comment]
@fredprod Shame on me. The problem is related to hostname seted in zabbix agent (yes, you ask me to check it. Sorry for that). I use chef to conf management. The chef set only the name insted of the FQDN. So, there are a mismatch between zabbix agent hostname (parsed by logstash.py) and zabbix server.

Sorry again for that. I'm using and create some new graphs and triggers. It's working like a charm.

Regards,

**Comment by fredprod** [comment]
@alanwds glad to see everything is ok now. Hostname is the first issue when using zabbix trapper ;)
I haven’t set a lot of graphs or screen in Template cause I’m using Grafana to graph. If you set interesting graphs and triggers, don’t hesitate to share with me, I could update Template o GitHu and share.zabbix.com as well.
Regards,

**Comment by alanwds** [comment]
@fredprod True story. As i said, my logstash server bind in local interface, so, i have to pass the FQDN parameter on User Parameters (to resolve to local interface):

```
UserParameter=logstash.check,/usr/local/bin/logstash.py -H logstash1.fqdn --update-items
UserParameter=logstash.discovery,/usr/local/bin/logstash.py -H logstash1.fqdn --discovery

```
Zabbix agent was configurated only with `logstash1`. The point is the endpoint `logstash1` does not resolve any DNS address. So, i had to do i small customization on the script:

```
simpleHostname = self.options.host.split(".fqdn")
self.hostname = simpleHostname[0];
```
It's working well :)

About the graphs: Great! What is the best way to share it with you (It's only 3 or 4 basic graphs and some triggers)?

Can you share you grafana dashboard (are consuming zabbix data source rigth)? I'm searching on https://grafana.com/dashboards and not found it.
Regards,

**Comment by fredprod** [comment]
Hi @alanwds, you can send me your modified template, and I can diff both. My grafana dashboards are consuming zabbix data source but ELK too for logs. I will look if I can push a logstash dashboard with only zabbix data source.
Regards,
